=encoding utf8

=head1 NAME

Regexp::Common::VATIN - Patterns for matching EU VAT Identification Numbers

=head1 SYNOPSIS
    use Regexp::Common qw(VATIN);
    "DE123456789" =~ $RE{VATIN}{DE};  # true
    "DE123456789" =~ $RE{VATIN}{any}; # true
    "LT123ABC"    =~ $RE{VATIN}{LT};  # false

=head1 DESCRIPTION

This module provides regular expression patterns to match any or all of the 26
nations levying a European Union value added tax.

=head1 SEE ALSO

=over

=item L<Regexp::Common>

For documentation of the interface this set of regular expressions uses.

=back

=head1 AUTHOR

Richard Simões C<< <rsimoes AT cpan DOT org> >>

=head1 COPYRIGHT AND LICENSE

Copyright © 2013 Richard Simões. This module is released under the terms of the
B<MIT License> and may be modified and/or redistributed under the same or any
compatible license.
